/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.jlguenego.prime;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
